CREATE TABLE IF NOT EXISTS `cake` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(100) NOT NULL,
	`description` TEXT NOT NULL,
	`image` VARCHAR(255) NOT NULL DEFAULT '',
	`rating` FLOAT NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`updated_at` TIMESTAMP,
	PRIMARY KEY(`id`)
);