version: '3.1'

services:
  mysql:
    image: mysql
    container_name: cake-store-mysql
    environment:
      MYSQL_DATABASE: 'cake-store'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/.docker/mysql:/var/lib/mysql