version: '3.1'

services:
  app:
    container_name: cake-service-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8081:8081
    restart: on-failure
    volumes:
      - ${HOME}/.docker/cake-service:/usr/src/app/
    depends_on:
      - mysql
    networks:
      - cake-service

  mysql:
    image: mysql
    container_name: cake-store-mysql
    environment:
      MYSQL_DATABASE: 'cake-store'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ${HOME}/.docker/mysql:/var/lib/mysql
    networks:
      - cake-service

networks:
  cake-service:
    driver: bridge